//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_config")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    /// 参数主键
    #[sea_orm(primary_key)]
    pub config_id: i32,
    /// 参数名称
    pub config_name: Option<String>,
    /// 参数键名
    pub config_key: Option<String>,
    /// 参数键值
    pub config_value: Option<String>,
    /// 参数类型
    pub config_type: Option<String>,
    /// 创建者
    pub create_by: Option<String>,
    /// 创建时间
    pub create_time: Option<DateTime<Utc>>,
    /// 更新者
    pub update_by: Option<String>,
    /// 更新时间
    pub update_time: Option<DateTime<Utc>>,
    /// 备注
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
