//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;
pub mod vo;

pub mod config;
pub mod dept;
pub mod menu;
pub mod post;
pub mod role;
pub mod role_dept;
pub mod role_menu;
pub mod user;
pub mod user_post;
pub mod user_role;

pub mod dict_data;
pub mod dict_type;

pub mod notice;
