//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_post")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    /// 岗位ID
    #[sea_orm(primary_key)]
    pub post_id: i64,
    /// 岗位编码
    pub post_code: String,
    /// 岗位名称
    pub post_name: String,
    /// 显示顺序
    pub post_sort: i32,
    /// 状态（0正常 1停用）
    pub status: String,
    /// 创建者
    pub create_by: Option<String>,
    /// 创建时间
    pub create_time: Option<DateTime<Utc>>,
    /// 更新者
    pub update_by: Option<String>,
    /// 更新时间
    pub update_time: Option<DateTime<Utc>>,
    /// 备注
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
