# 应用基本配置
[app]
name = "RuoYi-Rust"
version = "0.1.0"
copyright_year = "2025"
demo_enabled = false
upload_path = "upload"

# 服务器配置
[server]
host = "127.0.0.1"
port = 8080
# 工作线程数（0 表示使用 CPU 核心数）
# workers = 0
# 最大连接数
# max_connections: 25000
# 请求超时时间（秒）
# request_timeout: 30,
# 是否启用 HTTPS
# enable_https = false,
# SSL 证书路径
# ssl_cert: None,
# SSL 密钥路径
# ssl_key: None,

# JWT配置
[jwt]
secret = "ruoyi_rust_secret_key_for_development"
expires_in = 86400  # 24小时(秒)


# 数据库配置
[database]
url = "mysql://root:123456@localhost:3306/ruoyi"
# 最大连接数
# max_connections: 100,
# 最小连接数
# min_connections: 5,
# 连接超时时间（秒）
# connect_timeout: 10,
# 最大生命周期（秒）
# max_lifetime: 1800,
# 空闲超时时间（秒）
# idle_timeout: 600,

# 缓存配置,支持多级缓存
[cache]
# 默认开启 = true
enabled = true
# 默认类型 = local（local、redis、multi）
cache_type = "redis"
# [cache.local]
# name = "local"
# max_capacity = 10000
# default_ttl = 3600
# cleanup_interval = 60

[cache.redis]
# 连接类型 (standalone、cluster)
connection_type = "standalone"
# url (单机模式)
url = "redis://localhost:6379" 
# 主机地址（集群模式）
# hosts: Option<Vec<String>>,
# 密码
password = "123456"
# 数据库索引（仅单机模式有效）
# db: 0,
# 连接池最小空闲连接数
# min_idle: 5,
# 连接池最大连接数
# max_connections: 20,
# 连接超时时间（毫秒）
# connect_timeout: 10000,
# 命令超时时间（毫秒）
# command_timeout: 5000,
# 默认过期时间（秒）
# default_ttl: 3600,

# [cache.multi]
# 本地缓存过期时间（秒）- 通常比Redis设置更短以确保数据最终一致性
# local_ttl: 300,
# 是否在Redis连接失败时使用只读本地缓存模式
# fallback_to_local: true,