# 控制台 + 文件输出，按日轮转
refresh_rate: 30 seconds
appenders:
  console:
    kind: console
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S%.3f)}] [{l}] [{M}:{L}] {m}\n"
  file:
    kind: rolling_file
    path: "logs/app.log"
    append: true
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S%.3f)}] [{l}] [{M}:{L}] {m}\n"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: "logs/app.{}.log"
        count: 5
        base: 1
root:
  level: info
  appenders: [console, file]

loggers:
  actix_server:  # 过滤整个actix-server模块
    level: off   # 完全关闭
    additive: false
  sqlx:  # 过滤sqlx模块
    level: off
    additive: false
