//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::gen_table::{
    ActiveModel as GenTableActiveModel, Column as GenTableColumn, Entity as GenTableEntity,
    Model as GenTableModel,
};

pub use super::gen_table_column::{
    ActiveModel as GenTableColumnActiveModel, Column as GenTableColumnColumn,
    Entity as GenTableColumnEntity, Model as GenTableColumnModel,
};
